services:
  web:
    # image: xiaoxingan99/myapp:d05c63c643e6eafdf564661114e3c92f7377aa35
    image: xiaoxingan99/myapp:latest
    # build: ./projects/project1-ci-cd/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb