services:

  app-blue:
    image: xiaoxingan99/myapp:${TAG:-latest}
    container_name: app-blue
    environment:
      - COLOR=blue
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
    ports:
      - "3001:3000"
    depends_on:
      - db

  app-green:
    image: xiaoxingan99/myapp:${TAG:-latest}
    container_name: app-green
    environment:
      - COLOR=green
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
    ports:
      - "3002:3000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
   
    depends_on:
      - app-blue
      - app-green

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"