services:
  web:
    # image: xiaoxingan99/myapp
    build: ./projects/project1-ci-cd/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb