name: CD - Deploy Pipeline

on:
  workflow_run:
    workflows: ["CI - Build & Push"]
    types:
      - completed

  workflow_dispatch: {}
  
jobs:

  deploy-dev:
    if: github.event_name == 'workflow_run'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          $TAG = $env:GITHUB_SHA.Substring(0,7)
          docker pull xiaoxingan99/myapp:$TAG
          $env:TAG=$TAG
          docker compose up -d

  deploy-prod:
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: |
          $TAG = $env:GITHUB_SHA.Substring(0,7)
          docker pull xiaoxingan99/myapp:$TAG
          $env:TAG=$TAG
          docker compose up -d

  rollback:
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
      - run: |
          $LAST = Get-Content .last_deploy
          docker pull xiaoxingan99/myapp:$LAST
          $env:TAG=$LAST
          docker compose up -d  