name: CD - Deploy Production

on:
  workflow_run:
    workflows: ["CI - Build & Push"]
    types: [completed]

jobs:
  deploy:
    runs-on: self-hosted

    environment:
      name: production

    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: |
          $IMAGE_TAG = $env:GITHUB_SHA.Substring(0,7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $env:GITHUB_ENV

      - name: Pull Image
        run: |
          docker pull xiaoxingan99/myapp:${env:IMAGE_TAG}

      - name: Deploy
        run: |
          $env:TAG = $env:IMAGE_TAG
          docker compose up -d --force-recreate

      - name: Health Check
        run: |
          Start-Sleep -Seconds 10
          Invoke-WebRequest http://localhost:8080/health -UseBasicParsing