name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build & Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.WSL_HOST }}
          username: ${{ secrets.WSL_USER }}
          password: ${{ secrets.WSL_PASSWORD }}
          script: |
            set -e

            IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)

            docker pull xiaoxingan99/myapp:$IMAGE_TAG

            export TAG=$IMAGE_TAG
            docker compose up -d

            curl -f http://localhost:8080/health