name: CI - Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ⭐ Docker login（必须）
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build -t xiaoxingan99/myapp:${{ env.IMAGE_TAG }} ./projects/project1-ci-cd/app

      - name: Push Image
        run: |
          docker push xiaoxingan99/myapp:${{ env.IMAGE_TAG }}

      # ⭐ release tag（可选但推荐）
      - name: Create Git Tag
        run: |
          git tag v${GITHUB_SHA::7}
          git push origin v${GITHUB_SHA::7}