name: CI-CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy to WSL
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.WSL_HOST }}
          username: ${{ secrets.WSL_USER }}
          password: ${{ secrets.WSL_PASSWORD }}
          script: |
            cd ~/app
            docker compose pull
            docker compose up -d